language: rust
sudo: false
cache: cargo
rust:
  - nightly-2019-02-08
script:
  - cargo test --verbose --all --locked

matrix:
  include:

  - rust: nightly-2019-02-08
    script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
